TEXT_COLOR_PRIMARY = "#bfbdbd"
TEXT_COLOR_SECONDARY = "#b3b3b3"
BG_COLOR_CHAMP_SELECT_BUTTON_FALSE = "#ff303b"
BG_COLOR_CHAMP_SELECT_BUTTON_TRUE = "#27db27"
PADDING_X_MIN = 20
FONT_PRIMARY = ('Helvetica', 25)
FONT_SECONDARY = ('Helvetica', 12)
ERROR_FONT = ('Helvetica', 10)
POPUP_WINDOW_NAME = "Missing game path !!"
GAME_FILES_TEXT = "Enter the fullpath to League's instalation location"
CHAMPION_SELECT_FEATURE_TEXT = "Champion Select Feature"
START_PROCESS_BUTTON_TEXT = "Start"
STOP_PROCESS_BUTTON_TEXT = "Stop"

CHAMPION_ICONS_DIR = "res/champions/"
SUMMONER_SPELLS_DIR = "res/summoner_spells"
MATCH_FOUND_PHASE = "ReadyCheck"
CHAMP_SELECT_PHASE = "ChampSelect"
NUMBER_OF_COLUMNS = 3

ROOT_WINDOW_BACKGROUND_COLOR = "#39206b"
BORDER_COLOR = "#2b1852"